### ISSUE TITLE
Track properties regression in hyperHTML

### ISSUE THREAD

**Issue by oliverjanik** [webcomponents/custom-elements-everywhere#112] opened 2017-10-29 13:45 UTC
As per @WebReflection's comment here: https://github.com/WebReflection/hyperHTML/issues/138#issuecomment-340262339

the currently used hyperHTML version in the test is broken.

**Comment by robdodson** [comment] 2017-10-29 17:54
Yep our dependency bot [is on it](https://github.com/webcomponents/custom-elements-everywhere/pull/111). The new version is only a day old so haven't had a chance to catch up yet. I can merge it in now.

**Comment by robdodson** [comment] 2017-10-29 18:09
It looks like the tests are still failing in 1.12.5 - 1.12.0, but pass if I switch back to 1.11.4. So I guess there was a breaking change during the revision to 1.12.

Here's the component under test:

```js
export const ComponentWithProperties = (root) => hyper(root)`
  <div>
    <ce-with-properties id="wc"
      bool=${true}
      num=${42}
      str=${'hyperHTML'}
      arr=${['h', 'y', 'p', 'e', 'r', 'H', 'T', 'M', 'L']}
      obj=${{org: 'viperHTML', repo: 'hyperHTML'}}
    ></ce-with-properties>
  </div>`;
```

@oliverjanik @WebReflection could either of you tell me if the above looks like it has issues?

**Comment by WebReflection** [comment] 2017-10-29 20:56
1.12.3 was particularly problematic but if 1.12.5 still fails then there is a regression I need to address (yes, there were changes that might have affected the test).

Let the bot do its job, it'll be back to 30/30 soon. Thanks

**Comment by WebReflection** [comment] 2017-10-30 19:13
The changed introduced in 1.12 works better than 1.11 but it's slightly asynchronous due to a mechanism that avoids triggering of useless hyperhtml attributes when the template is created and parsed for the first time.

I'd like my users to know that hyperHTML works as expected and their CE prototypes with setters will also work as expected (as soon as the value is set).

There is a PR that fixexs those two tests by simply adding a delay and while this is a know gotcha that will be addressed in V2, to make hyperHTML compatible with A-Frame and standard `attributeChangedCallback` behavior the async change is needed.

V2 is planning to to force updates and trigger changes asycnhronously to every V0 or V1 element.

Please let me know if that PR looks reasonable, thanks.

**Comment by WebReflection** [comment] 2017-10-30 20:13
Thanks @robdodson !

@oliverjanik this repo shows (or will do it soon) 30/30 now

**Comment by robdodson** [comment] 2017-10-30 21:13
Should be fixed now.

**Closed by robdodson** 2017-10-30 21:13 UTC

**Comment by oliverjanik** [comment] 2017-10-31 05:19
bloody tops!
